/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "text-animate": {
    name: "text-animate",
    description:
      "Animated text component with customizable reveal effects and timing",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/text-animate.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/text-animate.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "texture-button": {
    name: "texture-button",
    description:
      "Button component with texture overlay effects and customizable variants",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/texture-button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/texture-button.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "texture-card": {
    name: "texture-card",
    description:
      "Card component with texture background and customizable styling options",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/texture-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/texture-card.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  timer: {
    name: "timer",
    description:
      "Countdown timer component with customizable duration and visual styles",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/timer.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/timer.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shift-card": {
    name: "shift-card",
    description:
      "Card component with shift animation effects and hover interactions",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/shift-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/shift-card.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "minimal-card": {
    name: "minimal-card",
    description:
      "Clean and minimal card component with subtle styling and hover effects",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/minimal-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/minimal-card.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dynamic-island": {
    name: "dynamic-island",
    description:
      "iOS-style dynamic island component with expandable content and smooth animations",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/dynamic-island.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/dynamic-island.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "direction-aware-tabs": {
    name: "direction-aware-tabs",
    description:
      "Tab component with direction-aware animations and smooth transitions",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/direction-aware-tabs.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/direction-aware-tabs.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-animate-button": {
    name: "bg-animate-button",
    description:
      "Button component with animated background effects and gradient transitions",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/bg-animate-button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/bg-animate-button.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "family-button": {
    name: "family-button",
    description:
      "Button component with family-style design and interactive hover effects",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/family-button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/family-button.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "side-panel": {
    name: "side-panel",
    description:
      "Sliding side panel component with customizable positioning and animations",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/side-panel.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/side-panel.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-media": {
    name: "bg-media",
    description:
      "Background media component with video/image support and overlay effects",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/bg-media.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/bg-media.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "three-d-carousel": {
    name: "three-d-carousel",
    description:
      "3D carousel component with perspective effects and smooth item transitions",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/three-d-carousel.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/three-d-carousel.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tweet-grid": {
    name: "tweet-grid",
    description:
      "Grid layout component for displaying tweet-like content cards",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/tweet-grid.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/tweet-grid.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gradient-heading": {
    name: "gradient-heading",
    description:
      "Heading component with gradient text effects and customizable styling",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/gradient-heading.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/gradient-heading.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  typewriter: {
    name: "typewriter",
    description:
      "Typewriter effect component with customizable typing speed and cursor animation",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/typewriter.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/typewriter.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-number": {
    name: "animated-number",
    description:
      "Number component with smooth counting animations and customizable formatting",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/animated-number.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/animated-number.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sortable-list": {
    name: "sortable-list",
    description:
      "Drag-and-drop sortable list component with smooth animations and reordering",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/sortable-list.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/sortable-list.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  dock: {
    name: "dock",
    description:
      "macOS-style dock component with hover effects and smooth animations",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/dock.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/dock.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  lightboard: {
    name: "lightboard",
    description:
      "Interactive lightboard component with customizable grid and lighting effects",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/lightboard.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/lightboard.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "canvas-fractal-grid": {
    name: "canvas-fractal-grid",
    description:
      "Interactive canvas-based fractal dot grid with mouse tracking and wave effects",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/canvas-fractal-grid.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/canvas-fractal-grid.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-animated-fractal-dot-grid": {
    name: "bg-animated-fractal-dot-grid",
    description:
      "Background animated fractal dot grid with performance optimization and responsive design",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/bg-animated-fractal-dot-grid.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/ui/bg-animated-fractal-dot-grid.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-animated-gradient": {
    name: "bg-animated-gradient",
    description:
      "Animated gradient background component with customizable color transitions",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/bg-animated-gradient.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/bg-animated-gradient.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-image-texture": {
    name: "bg-image-texture",
    description:
      "Background texture component with multiple texture variants and customizable opacity",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/bg-image-texture.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/bg-image-texture.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  popover: {
    name: "popover",
    description:
      "Animated popover component with form support and smooth transitions",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/popover.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/popover.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "floating-panel": {
    name: "floating-panel",
    description:
      "Floating panel component with backdrop blur and position-aware animations",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/floating-panel.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/floating-panel.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "color-picker": {
    name: "color-picker",
    description:
      "Interactive color picker component with HSL support and preset colors",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/color-picker.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/color-picker.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shader-lens-blur": {
    name: "shader-lens-blur",
    description:
      "WebGL shader component with lens blur effects and mouse interaction",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/shader-lens-blur.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/shader-lens-blur.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "popover-form": {
    name: "popover-form",
    description:
      "Form popover component with success states and animated transitions",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/popover-form.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/popover-form.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  expandable: {
    name: "expandable",
    description:
      "Expandable component system with smooth animations and customizable presets",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/expandable.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/expandable.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "logo-carousel": {
    name: "logo-carousel",
    description:
      "Animated logo carousel with staggered animations and customizable columns",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/logo-carousel.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/logo-carousel.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "loading-carousel": {
    name: "loading-carousel",
    description:
      "Loading carousel component with smooth transitions and customizable content",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/loading-carousel.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/loading-carousel.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "hover-video-player": {
    name: "hover-video-player",
    description:
      "Video player component that plays on hover with smooth animations",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/hover-video-player.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/hover-video-player.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "neumorph-eyebrow": {
    name: "neumorph-eyebrow",
    description:
      "Neumorphic eyebrow component with soft shadow effects and modern styling",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/neumorph-eyebrow.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/neumorph-eyebrow.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "neumorph-button": {
    name: "neumorph-button",
    description:
      "Neumorphic button component with soft shadows and tactile interaction effects",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/neumorph-button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/neumorph-button.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "feature-carousel": {
    name: "feature-carousel",
    description:
      "Feature carousel component with smooth transitions and customizable layouts",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/feature-carousel.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/feature-carousel.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choice-poll": {
    name: "choice-poll",
    description:
      "Poll component with single or multiple selection, optional results, and keyboard navigation",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/choice-poll.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/choice-poll.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "vote-tally": {
    name: "vote-tally",
    description:
      "List of items with up-vote support, optional sorting by vote count, and controlled or uncontrolled state",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/vote-tally.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/vote-tally.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "poll-widget": {
    name: "poll-widget",
    description:
      "Poll widget with inline, popover, and dialog modes, optional results, and animations",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/poll-widget.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/poll-widget.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "prompt-library": {
    name: "prompt-library",
    description:
      "Browse, insert, and manage prompt templates with categories and custom prompts",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/prompt-library.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/prompt-library.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ai-instructions": {
    name: "ai-instructions",
    description:
      "Manage and toggle AI instructions with a popover, search, and create-dialog",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/ai-instructions.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/ai-instructions.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "intro-disclosure": {
    name: "intro-disclosure",
    description:
      "Intro disclosure component with expandable content and smooth animations",
    type: "registry:ui",
    registryDependencies: ["button", "aspect-ratio"],
    files: [
      {
        path: "registry/default/ui/intro-disclosure.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/intro-disclosure.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-gif": {
    name: "text-gif",
    description:
      "Text component with GIF-like animation effects and customizable styling",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/text-gif.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/text-gif.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stripe-bg-guides": {
    name: "stripe-bg-guides",
    description:
      "Stripe-style background guides component with animated patterns and effects",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/stripe-bg-guides.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/stripe-bg-guides.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "youtube-video-player": {
    name: "youtube-video-player",
    description:
      "YouTube video player component with custom controls and smooth animations",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [
      {
        path: "registry/default/ui/youtube-video-player.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/youtube-video-player.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "toolbar-expandable": {
    name: "toolbar-expandable",
    description:
      "Expandable toolbar component with step-based navigation, smooth animations, and enhanced scrolling",
    type: "registry:ui",
    registryDependencies: ["badge"],
    files: [
      {
        path: "registry/default/ui/toolbar-expandable.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/toolbar-expandable.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "texture-overlay": {
    name: "texture-overlay",
    description:
      "Texture overlay component with various CSS gradient patterns for adding visual texture to backgrounds",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/texture-overlay.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/texture-overlay.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "squiggle-arrow": {
    name: "squiggle-arrow",
    description:
      "A playful, hand-drawn squiggly arrow component with customizable variants, directions, and sizes",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/squiggle-arrow.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/squiggle-arrow.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "code-block": {
    name: "code-block",
    description:
      "A beautiful code block component with tabs, copy functionality, and smooth animations",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/code-block.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/code-block.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mock-browser-window": {
    name: "mock-browser-window",
    description:
      "A customizable browser window mockup component with support for Chrome, Safari, and generic styles, customizable sidebars, and themes",
    type: "registry:ui",
    registryDependencies: ["texture-overlay"],
    files: [
      {
        path: "registry/default/ui/mock-browser-window.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/mock-browser-window.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "morph-surface": {
    name: "morph-surface",
    description:
      "A morphing surface component with smooth animations, customizable dimensions, and configurable content",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/morph-surface.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/morph-surface.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "distorted-glass": {
    name: "distorted-glass",
    description:
      "A glass morphism effect component using SVG filters with fractal noise to create visual transitions between sections",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/distorted-glass.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/distorted-glass.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "family-drawer": {
    name: "family-drawer",
    description:
      "A multi-view drawer component with smooth animations, view navigation, and customizable content views",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/family-drawer.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/family-drawer.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "expandable-screen": {
    name: "expandable-screen",
    description:
      "A full-screen expandable component with morphing animations using shared layout IDs for smooth transitions",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/expandable-screen.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/expandable-screen.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pixel-heading-character": {
    name: "pixel-heading-character",
    description:
      "Per-character pixel-font heading with four animation modes using Geist pixel fonts",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/pixel-heading-character.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/ui/pixel-heading-character.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pixel-heading-word": {
    name: "pixel-heading-word",
    description:
      "Whole-word pixel-font heading that swaps or cycles fonts on hover using Geist pixel fonts",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/pixel-heading-word.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/pixel-heading-word.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pixel-paragraph-words-inverse": {
    name: "pixel-paragraph-words-inverse",
    description:
      "Paragraph in pixel font where specific words escape into interactive sans/mono with hover swap or cycle",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/pixel-paragraph-words-inverse.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/ui/pixel-paragraph-words-inverse.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pixel-paragraph-words": {
    name: "pixel-paragraph-words",
    description:
      "Paragraph where specific words render in an interactive pixel font that swaps or cycles on hover",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/pixel-paragraph-words.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/ui/pixel-paragraph-words.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-animate-demo": {
    name: "text-animate-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["text-animate"],
    files: [
      {
        path: "registry/default/example/text-animate-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/text-animate-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "texture-button-demo": {
    name: "texture-button-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["texture-button"],
    files: [
      {
        path: "registry/default/example/texture-button-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/texture-button-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "texture-card-demo": {
    name: "texture-card-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["texture-card", "texture-button"],
    files: [
      {
        path: "registry/default/example/texture-card-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/texture-card-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "timer-demo": {
    name: "timer-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["timer", "texture-button"],
    files: [
      {
        path: "registry/default/example/timer-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/timer-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shift-card-demo": {
    name: "shift-card-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["shift-card", "texture-button"],
    files: [
      {
        path: "registry/default/example/shift-card-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/shift-card-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "minimal-card-demo": {
    name: "minimal-card-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["minimal-card"],
    files: [
      {
        path: "registry/default/example/minimal-card-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/minimal-card-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dynamic-island-demo": {
    name: "dynamic-island-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["dynamic-island"],
    files: [
      {
        path: "registry/default/example/dynamic-island-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/dynamic-island-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "direction-aware-tabs-demo": {
    name: "direction-aware-tabs-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["direction-aware-tabs"],
    files: [
      {
        path: "registry/default/example/direction-aware-tabs-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/direction-aware-tabs-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-animate-button-demo": {
    name: "bg-animate-button-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["bg-animate-button"],
    files: [
      {
        path: "registry/default/example/bg-animate-button-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/bg-animate-button-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "family-button-demo": {
    name: "family-button-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["family-button"],
    files: [
      {
        path: "registry/default/example/family-button-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/family-button-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "side-panel-demo": {
    name: "side-panel-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["side-panel"],
    files: [
      {
        path: "registry/default/example/side-panel-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/side-panel-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-media-demo": {
    name: "bg-media-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["bg-media"],
    files: [
      {
        path: "registry/default/example/bg-media-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/bg-media-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-image-texture-demo": {
    name: "bg-image-texture-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["bg-image-texture"],
    files: [
      {
        path: "registry/default/example/bg-image-texture-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/bg-image-texture-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "three-d-carousel-demo": {
    name: "three-d-carousel-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["three-d-carousel"],
    files: [
      {
        path: "registry/default/example/three-d-carousel-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/three-d-carousel-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tweet-grid-demo": {
    name: "tweet-grid-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["tweet-grid", "gradient-heading"],
    files: [
      {
        path: "registry/default/example/tweet-grid-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/tweet-grid-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gradient-heading-demo": {
    name: "gradient-heading-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["gradient-heading"],
    files: [
      {
        path: "registry/default/example/gradient-heading-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/gradient-heading-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "typewriter-demo": {
    name: "typewriter-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["typewriter"],
    files: [
      {
        path: "registry/default/example/typewriter-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/typewriter-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-number-demo": {
    name: "animated-number-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["animated-number"],
    files: [
      {
        path: "registry/default/example/animated-number-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/animated-number-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sortable-list-demo": {
    name: "sortable-list-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["sortable-list"],
    files: [
      {
        path: "registry/default/example/sortable-list-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/sortable-list-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dock-demo": {
    name: "dock-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["dock"],
    files: [
      {
        path: "registry/default/example/dock-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/dock-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "lightboard-demo": {
    name: "lightboard-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["lightboard"],
    files: [
      {
        path: "registry/default/example/lightboard-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/lightboard-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "canvas-fractal-grid-demo": {
    name: "canvas-fractal-grid-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["canvas-fractal-grid"],
    files: [
      {
        path: "registry/default/example/canvas-fractal-grid-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/canvas-fractal-grid-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-animated-fractal-dot-grid-demo": {
    name: "bg-animated-fractal-dot-grid-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["bg-animated-fractal-dot-grid"],
    files: [
      {
        path: "registry/default/example/bg-animated-fractal-dot-grid-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/bg-animated-fractal-dot-grid-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bg-animated-gradient-demo": {
    name: "bg-animated-gradient-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["bg-animated-gradient"],
    files: [
      {
        path: "registry/default/example/bg-animated-gradient-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/bg-animated-gradient-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "popover-demo": {
    name: "popover-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["popover"],
    files: [
      {
        path: "registry/default/example/popover-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/popover-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "floating-panel-demo": {
    name: "floating-panel-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["floating-panel"],
    files: [
      {
        path: "registry/default/example/floating-panel-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/floating-panel-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "color-picker-demo": {
    name: "color-picker-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["color-picker"],
    files: [
      {
        path: "registry/default/example/color-picker-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/color-picker-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shader-lens-blur-demo": {
    name: "shader-lens-blur-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["shader-lens-blur", "color-picker"],
    files: [
      {
        path: "registry/default/example/shader-lens-blur-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/shader-lens-blur-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "popover-form-demo": {
    name: "popover-form-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["popover-form"],
    files: [
      {
        path: "registry/default/example/popover-form-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/popover-form-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "expandable-demo": {
    name: "expandable-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["expandable"],
    files: [
      {
        path: "registry/default/example/expandable-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/expandable-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "logo-carousel-demo": {
    name: "logo-carousel-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["logo-carousel", "gradient-heading"],
    files: [
      {
        path: "registry/default/example/logo-carousel-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/logo-carousel-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "loading-carousel-demo": {
    name: "loading-carousel-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["loading-carousel"],
    files: [
      {
        path: "registry/default/example/loading-carousel-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/loading-carousel-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "hover-video-player-demo": {
    name: "hover-video-player-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["hover-video-player"],
    files: [
      {
        path: "registry/default/example/hover-video-player-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/hover-video-player-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "neumorph-eyebrow-demo": {
    name: "neumorph-eyebrow-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["neumorph-eyebrow"],
    files: [
      {
        path: "registry/default/example/neumorph-eyebrow-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/neumorph-eyebrow-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "neumorph-button-demo": {
    name: "neumorph-button-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["neumorph-button"],
    files: [
      {
        path: "registry/default/example/neumorph-button-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/neumorph-button-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "feature-carousel-demo": {
    name: "feature-carousel-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["feature-carousel"],
    files: [
      {
        path: "registry/default/example/feature-carousel-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/feature-carousel-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choice-poll-demo": {
    name: "choice-poll-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["choice-poll"],
    files: [
      {
        path: "registry/default/example/choice-poll-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/choice-poll-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "vote-tally-demo": {
    name: "vote-tally-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["vote-tally"],
    files: [
      {
        path: "registry/default/example/vote-tally-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/vote-tally-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "poll-widget-demo": {
    name: "poll-widget-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["poll-widget"],
    files: [
      {
        path: "registry/default/example/poll-widget-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/poll-widget-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "prompt-library-demo": {
    name: "prompt-library-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["prompt-library"],
    files: [
      {
        path: "registry/default/example/prompt-library-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/prompt-library-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ai-instructions-demo": {
    name: "ai-instructions-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["ai-instructions"],
    files: [
      {
        path: "registry/default/example/ai-instructions-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/ai-instructions-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "intro-disclosure-demo": {
    name: "intro-disclosure-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["intro-disclosure"],
    files: [
      {
        path: "registry/default/example/intro-disclosure-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/intro-disclosure-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-gif-demo": {
    name: "text-gif-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["text-gif"],
    files: [
      {
        path: "registry/default/example/text-gif-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/text-gif-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stripe-bg-guides-demo": {
    name: "stripe-bg-guides-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["stripe-bg-guides"],
    files: [
      {
        path: "registry/default/example/stripe-bg-guides-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/stripe-bg-guides-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "youtube-video-player-demo": {
    name: "youtube-video-player-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["youtube-video-player"],
    files: [
      {
        path: "registry/default/example/youtube-video-player-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/youtube-video-player-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "toolbar-expandable-demo": {
    name: "toolbar-expandable-demo",
    description: "",
    type: "registry:component",
    registryDependencies: [
      "toolbar-expandable",
      "button",
      "input",
      "label",
      "textarea",
    ],
    files: [
      {
        path: "registry/default/example/toolbar-expandable-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/toolbar-expandable-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "texture-overlay-demo": {
    name: "texture-overlay-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["texture-overlay"],
    files: [
      {
        path: "registry/default/example/texture-overlay-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/texture-overlay-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "squiggle-arrow-demo": {
    name: "squiggle-arrow-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["squiggle-arrow"],
    files: [
      {
        path: "registry/default/example/squiggle-arrow-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/squiggle-arrow-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "code-block-demo": {
    name: "code-block-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["code-block"],
    files: [
      {
        path: "registry/default/example/code-block-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/code-block-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mock-browser-window-demo": {
    name: "mock-browser-window-demo",
    description: "",
    type: "registry:component",
    registryDependencies: [
      "mock-browser-window",
      "button",
      "input",
      "label",
      "select",
      "switch",
    ],
    files: [
      {
        path: "registry/default/example/mock-browser-window-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/mock-browser-window-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "morph-surface-demo": {
    name: "morph-surface-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["morph-surface"],
    files: [
      {
        path: "registry/default/example/morph-surface-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/morph-surface-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "distorted-glass-demo": {
    name: "distorted-glass-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["distorted-glass"],
    files: [
      {
        path: "registry/default/example/distorted-glass-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/distorted-glass-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "family-drawer-demo": {
    name: "family-drawer-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["family-drawer"],
    files: [
      {
        path: "registry/default/example/family-drawer-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/family-drawer-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "expandable-screen-demo": {
    name: "expandable-screen-demo",
    description: "",
    type: "registry:component",
    registryDependencies: [
      "expandable-screen",
      "button",
      "input",
      "label",
      "select",
      "textarea",
    ],
    files: [
      {
        path: "registry/default/example/expandable-screen-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/expandable-screen-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pixel-heading-character-demo": {
    name: "pixel-heading-character-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["pixel-heading-character"],
    files: [
      {
        path: "registry/default/example/pixel-heading-character-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/pixel-heading-character-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pixel-heading-word-demo": {
    name: "pixel-heading-word-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["pixel-heading-word"],
    files: [
      {
        path: "registry/default/example/pixel-heading-word-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/pixel-heading-word-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pixel-paragraph-words-inverse-demo": {
    name: "pixel-paragraph-words-inverse-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["pixel-paragraph-words-inverse"],
    files: [
      {
        path: "registry/default/example/pixel-paragraph-words-inverse-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/pixel-paragraph-words-inverse-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pixel-paragraph-words-demo": {
    name: "pixel-paragraph-words-demo",
    description: "",
    type: "registry:component",
    registryDependencies: ["pixel-paragraph-words"],
    files: [
      {
        path: "registry/default/example/pixel-paragraph-words-demo.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/pixel-paragraph-words-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}
