import { exec } from "child_process"
import { promises as fs } from "fs"
import path from "path"

import { registry } from "../registry/index"

async function buildRegistryIndex() {
  let index = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import { defineAsyncComponent } from "vue"

export const Index: Record<string, any> = {`
  for (const item of registry.items) {
    if (!item.files?.length) {
      continue
    }

    const componentPath = item.files[0]?.path
      ? `@/${item.files[0].path}`
      : ""

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files.map((file: { path: string; type: string; target?: string }) => {
      const filePath = file.path
      return `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`
    })}],
    component: ${
      componentPath
        ? `defineAsyncComponent(() => import("${componentPath}"))`
        : "null"
    },
  },`
  }

  index += `
}`

  console.log(`#  ${registry.items.length} items found`)

  await fs.writeFile(
    path.join(process.cwd(), "registry/__index__.ts"),
    index
  )
}

async function buildRegistryJsonFile() {
  await fs.writeFile(
    path.join(process.cwd(), "registry.json"),
    JSON.stringify(registry, null, 2)
  )

  const outputDir = path.join(
    process.cwd(),
    "public/r/styles/default"
  )
  await fs.mkdir(outputDir, { recursive: true })
  await fs.cp(
    path.join(process.cwd(), "registry.json"),
    path.join(outputDir, "registry.json")
  )
}

async function buildRegistry() {
  return new Promise<void>((resolve, reject) => {
    const child = exec(
      `pnpm dlx shadcn-vue build registry.json --output public/r/styles/default`
    )

    let stderr = ""
    child.stderr?.on("data", (data) => { stderr += data })
    child.stdout?.pipe(process.stdout)

    child.on("exit", (code) => {
      if (code === 0) {
        resolve()
      } else {
        reject(new Error(`shadcn-vue build failed (code ${code}): ${stderr}`))
      }
    })
  })
}

try {
  // buildRegistryIndex and buildRegistryJsonFile are independent
  console.log("Building registry/__index__.ts and registry.json...")
  await Promise.all([buildRegistryIndex(), buildRegistryJsonFile()])

  console.log("Building registry...")
  await buildRegistry()
} catch (error) {
  console.error(error)
  process.exit(1)
}
